# Generated by Django 5.0 on 2024-04-27 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('process', models.TextField()),
                ('image1', models.ImageField(upload_to='RecipeImages')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='RecipeImages')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='RecipeImages')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='RecipeImages')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
